{% set name = "gwtrigfind" %}
{% set version = "0.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8005a5fa6bb434ac99b1765ca26e44be3ab947229153df75e2998c293a51d0e4

build:
  number: 0
  noarch: python
  entry_points:
    - gwtrigfind=gwtrigfind.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - gpstime
    - ligo-segments >=1.0.0
    - python

test:
  imports:
    - gwtrigfind
  requires:
    - pytest
  commands:
    - gwtrigfind --help
    - python -m gwtrigfind --help
    - python -m pytest --pyargs gwtrigfind  # [not win]

about:
  home: https://github.com/gwpy/gwtrigfind
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Utility to find files archived by GW event trigger generators
  description: |
    A utility to find GW trigger files produced by event trigger generators
    and archived on the LIGO Data Grid.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - eagoetz
    - areeda
