{% set name = "gwtrigfind" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6caf0d66135e90977e2d8529fef5da0ecff4e00830e1b2ebbe9fcd5f229b3e8d

build:
  number: 0
  noarch: python
  entry_points:
    - gwtrigfind=gwtrigfind.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - astropy
    - ligo-segments >=1.0.0
    - python

test:
  imports:
    - gwtrigfind
  requires:
    - pytest
  commands:
    - gwtrigfind --help
    - python -m gwtrigfind --help
    - python -m pytest --pyargs gwtrigfind  # [not win]

about:
  home: https://github.com/gwpy/gwtrigfind
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Utility to find files archived by GW event trigger generators
  description: |
    A utility to find GW trigger files produced by event trigger generators
    and archived on the LIGO Data Grid.

extra:
  recipe-maintainers:
    - duncanmmacleod
