{% set name = "gwtrigfind" %}
{% set version = "0.8.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c656b8fb4fc6f4089528a81211a3e7ac66ff2fb269e1db2b1d96ba4a8194f0e3

build:
  number: 0
  noarch: python
  entry_points:
    - gwtrigfind = gwtrigfind.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - gpstime
    - igwn-segments >=1.0.0
    - python >={{ python_min }}

test:
  imports:
    - gwtrigfind
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - gwtrigfind --help
    - python -m gwtrigfind --help
    - python -m pytest --pyargs gwtrigfind  # [not win]

about:
  home: https://git.ligo.org/detchar/tools/gwtrigfind
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Utility to find files archived by GW event trigger generators
  description: |
    A utility to find GW trigger files produced by event trigger generators
    and archived on the LIGO Data Grid.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - eagoetz
    - areeda
