travis:
  secure:
    BINSTAR_TOKEN: 1JojaDS1XFOKrpD9NGrCQMWMFHrxy4wCwS+fbFaOh/c7SaN43w7JPMXieFKAvlVU6XaRavPnl2vfEC1iMZS4ftRqCX36d3KXLn5wArD0qjOaX3Jba2euh3OlNrcReAIiak8mwnDww7N4ga6Ug71NH4zBX46qrCopkpQbXMckmnh/mAfidi5mdhlW7lGmt6r5o6LGZDR9y8h/GNGUAtwT0ZbpHG7I4+kxE1R0FKZ5v10QenXpZoS8NFvMYROLYN1qai8czgQZGAEHRzMZdaCwFGBw/KVDXlox/8YgbU2vDA0agaO5TUmmDVtJNmang/5Wh0sGmZTzPirS3MGLHjXbuBug0Twdr/N75IP4zvRdqiFJ7CtDN0ix27tlaLnnJvliakooWDFvHEe+AR2q2rLmQB4s8dVbiwBMy90ULYiFrzv8G1Urcgat+JnMEG6F94JLPUuRW7m/Wti7s5fSNU2Wg2lNMBzSX4LoL929mAnNQqHlMUHeKndLQULmu9M3T37qaTweFxhhfvKEiuZNSHyvpTfYcfDoREZGNLBjn5RFOMQup51UboubLpekEgRRM7G6INzxpRYCFnfxMHPEQ5eJn6GeLXAjOyEkLhL9aaTBXAd2omnlN780apRQxLS6IymvbNar/i+UoeLdSbZZr7RosseaqFqZMrqGAlmUShRPlJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
